version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=altbau_vs_neubau
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

  github-runner:
    image: actions/runner:latest
    restart: always
    environment:
      - REPO_URL=${GITHUB_REPO_URL:-https://github.com/SWProjectTin23/altbauVsNeubau}
      - RUNNER_NAME=${GITHUB_RUNNER_NAME:-github-runner-altbau-vs-neubau}
      - ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - RUNNER_LABELS= self-hosted,docker,linux,altbau_vs_neubau
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data: