apiVersion: 1
groups:
    - orgId: 1
      name: altbauvsneubau
      folder: main
      interval: 10s
      rules:
        - uid: aevh26uxfx2wwb
          title: Arduino offline
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fevdvif8bpb7kc
              model:
                editorMode: code
                expr: sensor_seconds_since_last_data{device_id=~".+"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 240
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            description: ""
            runbook_url: ""
            summary: Arduino {{ $labels.device_id }} offline seit {{ $values.A }} Sekunden
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
