apiVersion: 1
groups:
    - orgId: 1
      name: sensor-alerts
      folder: main
      interval: 30s
      rules:
        - uid: aewe226ek8mioc
          title: Sensor-offline
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: fevdvif8bpb7kc
              model:
                datasource:
                    type: prometheus
                    uid: fevdvif8bpb7kc
                editorMode: code
                expr: sensor_seconds_since_last_data{device_id=~".+", sensor_type=~".+"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 600
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            summary: |-
                Folgende Sensoren sind offline:
                {{ range $values.A }}
                  Gerät: {{ .labels.device_id }}, Sensor: {{ .labels.sensor_type }}, Zeit: {{ .value }} Sekunden
                {{ end }}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-arduino-offline-email