apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb        
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: db:5432
    user: postgres
    secureJsonData:
      password: Svk63ajSYDaQkuVK
    database: altbau_vs_neubau
    jsonData:
      postgresVersion: 1400
      sslmode: "disable"
      timescaledb: true

  - name: Prometheus
    uid: fevdvif8bpb7kc
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: Loki
    uid: loki            # <— WICHTIG: muss 'loki' heißen, damit dein Dashboard passt
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
