name: CI/CD Deployment to Self-Hosted Runner
# This GitHub Actions workflow deploys your application to a self-hosted runner using Docker Compose
# It is triggered on every push to the 'main' branch.

on:
  push:
    branches:
      - main # The workflow will be triggered on every push to the 'main' branch
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  deploy:
    runs-on: [self-hosted, linux, altbau_vs_neubau] # Specifies that the job should run on a self-hosted Linux runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Fetches your repository's code onto the runner

    - name: Set up Docker Compose and Deploy
      run: |
        echo "Deploying application using Docker Compose..."
        docker compose -f docker-compose.yml down # Stops and removes containers, networks, images, and volumes defined in the docker-compose.yml file
        
        # Build and start the containers defined in the docker-compose.yml file
        echo "Pulling latest Docker images..."
        docker compose pull # Pulls the latest images for the services defined in the docker-compose.yml file

        # Build and start the containers
        echo "Building Docker images..."
        docker compose build

        echo "Starting new containers..."
        # Start the containers in detached mode
        docker compose up -d

        echo "Application deployed successfully!"
