name: Build and Push Docker Images to GHCR and Deploy on Server

on:
  push:
    branches:
      - main
      - feature/deployment

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push backend-api image
        run: |
          docker build -t ghcr.io/geroldj/altbauvsneubau/backend-api:latest -f ./backend/Dockerfile.api ./backend
          docker push ghcr.io/geroldj/altbauvsneubau/backend-api:latest

      - name: Build and push backend-mqtt image
        run: |
          docker build -t ghcr.io/geroldj/altbauvsneubau/backend-mqtt:latest -f ./backend/Dockerfile.mqtt ./backend
          docker push ghcr.io/geroldj/altbauvsneubau/backend-mqtt:latest

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/geroldj/altbauvsneubau/frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ghcr.io/geroldj/altbauvsneubau/frontend:latest

      - name: Build and push sensor exporter image
        run: |
          docker build -t ghcr.io/geroldj/altbauvsneubau/sensor-exporter:latest -f ./sensor-exporter/Dockerfile .
          docker push ghcr.io/geroldj/altbauvsneubau/sensor-exporter:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy via SSH with Git + Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /altbauVsNeubau   
            git reset --hard
            git pull

            docker-compose -f docker-compose-prod.yml pull
            docker-compose -f docker-compose-prod.yml up -d
