name: Python Tests

on:
    pull_request:
        branches:
            - main
       
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'  # Oder deine Version

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests with coverage
          run: |
            pytest tests/ --maxfail=1 --disable-warnings --cov=backend --cov-report=term-missing

        - name: Upload coverage report
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: coverage-report
            path: htmlcov/