name: Python Tests

on:
    pull_request:
        branches:
            - main
       
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'  # Oder deine Version
        - name: Export environment variables from secrets
          run: |
            echo "MQTT_BROKER=${{ secrets.MQTT_BROKER }}" >> $GITHUB_ENV
            echo "MQTT_PORT=${{ secrets.MQTT_PORT }}" >> $GITHUB_ENV
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
            echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r backend/requirements.txt

        - name: Debug - show current directory and files
          run: |
            pwd
            ls -la
            ls -la backend

        - name: Set PYTHONPATH
          run: echo "PYTHONPATH=$PYTHONPATH:./backend" >> $GITHUB_ENV

        - name: Run tests with coverage
          run: |
            export PYTHONPATH=backend
            python -m pytest backend/tests/ --maxfail=1 --disable-warnings --cov=backend --cov-report=term-missing


        - name: Upload coverage report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: htmlcov/